services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: vaxshopdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:7-alpine

  django:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - media_files:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file: .env

  celery:
    build: .
    command: celery -A config worker -l info -B
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    env_file: .env

volumes:
  postgres_data:
  media_files:
